MoralisWeb3/Moralis-JS-SDK

src/UnitConvert.js

Added `Moralis.Unit.FromWei` for converting tokens from `Wei` with different numbers of decimals. Returns `number`

feat: add converter Moralis.Unit.FromWei 

---

src/MoralisWalletConnectProvider.js

Improved code to correctly add options for available wallets for WC

fix: Fixed mobileLinking option for WC

---

src/MoralisWeb3.js

An option to add custom signMessage for linking address added

feat: signingMessage added for linking wallet

---

types/generated/web3Api.d.ts

---
---
Update autogenerated web3 API types

update web3api types

---

src/MoralisWeb3.js

---
---
Improve missing web3 error message by specifying to use `authenticate`

update web3missing error message

---

types/index.d.ts

add msgValue type for executeFunction

---

package-lock.json
package.json

---
name: 'Update ws'
about: Update vulnerabile package
---

update ws to 7.4.6

---

scripts/genWeb3API.js
src/MoralisWeb3Api.js

fix: export default web3api

---

src/MoralisWeb3.js

---
---
Add a new plugin trigger that allows to sign a message following `EIP-712` (`eth_signTypedData_v4`)
Docs: https://docs.metamask.io/guide/signing-data.html#sign-typed-data-v4
Enable sign V4

Update: Add new plugin trigger

---

src/MoralisCustomProvider.js
src/MoralisWalletConnectProvider.js
types/generated/web3Api.d.ts
types/index.d.ts

---
name: 'Fantom Support'
about: Fantom support in the SDK
---
Added chain Ids and other references to Fantom network.
Also added missing references for Avalanche

Added Fantom support

---

.gitlab-ci.yml

---
about: commit generated files before pushing after release
---

commit generated files before pushing in pipeline

---

.gitignore

---
about: Add .npmrc to .gitignore file to prevent token update
---

ignore .npmrc

---

src/MoralisCustomProvider.js
src/MoralisWalletConnectProvider.js
types/generated/web3Api.d.ts
types/index.d.ts

---
name: 'Avalanche Testnet Support'
---
Added support for Avalanche testnet

Added avalanche testnet

---

src/MoralisWeb3.js

---
about: openUrl trigger refactor
---
Refactoring plugin triggers involve AST refactor + plugin + sdk.
This is the refactoring related to 'openUrl' trigger.

Refactor: openUrl trigger

---

src/utils.js

---
---
Requesting version info from npm results in a  failing preflight check on firefox and results in a CORS issue.
- Using unpkg as domain to fetch the latest version
- Updated the check to compare versions to account for any semantic versioning

fix: cors error on version check

---

src/Parse.js

---
about: Remove info message when using node without moralis secret
---

remove node warning in moralis.start

---

src/MoralisWeb3.js

---
---
`Moralis.getChainId()` returns chainId `1` for avalanche instead of `43114`
web3.eth.net.getId() changed to web3.eth.getChainId()

network detection method changed

---

README.md

---
about: running SDK on Webpack v5 info added
---

Update README.md Webpack v5 support

---

.gitlab-ci.yml
package-lock.json
package.json
release.config.js

ci: use semantic-release for publishing

---

src/Chians.js
src/Parse.js
types/index.d.ts

---
Added Enums for Supported chains.
---

Added Enums For Chains

---

CHANGELOG.md
package-lock.json
src/Parse.js

chore: fix merge conflicts

---

types/index.d.ts

fix: typings for ethers

---

.github/dependabot.yml

ci: update dependabot prefix for non dev deps

---

src/Web3Connector/WalletConnectWeb3Connector.js

---
---
Walletconnect import fails on CDN
Account for CDN builds by checking the window

fix: walletconnect import on CDN builds

---

src/MoralisWeb3.js

---
---
Connector and provider info was not emitted for `onDisconnect` event
Fire the event before removing references

fix: include details on WEB3_DEACTIVATED event

---

types/index.d.ts

fix: move MoralisWeb3 types to Moralis

---

src/Parse.js
src/filterConsole.js

fix: filter out walletconnect dependency warning

---

src/MoralisWeb3.js
src/Storage.js
src/__tests__/Storage-test.js
types/index.d.ts

---
---
No access to the Ethers library
Expose the ethersLibrary via Moralis.web3Library

Expose web3library

---

scripts/genSolanaAPI.js
scripts/genWeb3API.js
src/MoralisSolanaApi.js
src/MoralisWeb3Api.js

fix: set default address for Web3API and SolanaAPI

---

src/InternalWeb3Provider.js
src/MoralisWeb3.js

---
---
Ethers.js throws an error when network is not in line when user switches network.
Update the web3 instance onChainChange

fix: update web3 on chainChange

---

src/ParseUser.js

fix: clear user state on logout

---

src/filterConsole.js

fix: filter console warnings of magic and wc

---

src/MoralisWeb3.js

---
---
Fix several issues related to cleanup right and authentication

Fix  prevent cleanup when enabling web3

---

types/index.d.ts

---
---
Fix Typescript issue for `anyNetwork` in enableWeb3

fix: types for anyNetwork in enableWeb3

---

src/MoralisWeb3.js

---
---
Overloaded functions do not work
Related issue: https://github.com/MoralisWeb3/Moralis-JS-SDK/pull/247
Functions that have overloaded function definitions should be called with a topic `getMessage(string)`
If an abi has multiple definitions, and no topic is specified in the functionName; an error will be thrown
If no abi definition can be found for the provided functionName+topic, an error will be thrown
If the functionName+topic is valid, then the correct functionData will be selected from the abi, validation checks will run and the contract is called with `functionName(topic)`, as expected by EthersJs

fix: overloaded functions for executeFunction

---

types/index.d.ts

fix: FromWei type

---

src/MoralisDot.js
src/MoralisErd.js
src/MoralisSol.js
src/MoralisWeb3.js

fix: use secure signing message for link action

---

types/index.d.ts

---
---
Add missing type for User.me

fix: add missing type for User.me

---

scripts/genSolanaAPI.js
scripts/genWeb3API.js
src/MoralisSolanaApi.js
src/MoralisWeb3Api.js

---
---
Related issue: https://github.com/MoralisWeb3/Moralis-JS-SDK/issues/267
Prevent deletion of original params when making web3 or solana api call

fix: prevent deletion of params in api call

---

src/MoralisWeb3.js

---
about: Skip validation for executeFunction
---

remove validation for inputs with empty name value

---

src/Parse.js
src/utils.js

added endpoint to track and implemented in start function

---

package-lock.json
package.json

This is causing issues as it exports only esm
---
---

fix: revert openapi-typescript

---

release.config.js

---
---
Add repository url for semantic release

fix: add repository url for semantic release

---

package-lock.json
package.json

Manual bump sto trigger semantic-release
---
---

fix: plugin triggers to handle web3sign correctly

---

scripts/genWeb3API.js
scripts/generateWeb3ApiTypes.js
src/MoralisWeb3Api.js
types/generated/web3Api.d.ts

---
name: 'Web3api pagination'
about: This pull request implements pagination when using web3api seamlessly by calling `await response.next()`
---

feat(api-pagination): Integrating pagination on web3api

---

src/MoralisUI.js
src/Parse.js
src/ParseQuery.js
src/Web3Connector/NetworkWeb3Connector.js
src/__tests__/browser-test.js
src/utils.js

add moralis id to console logs
---
about: moralis identification to warnings and errors so the user can know that this warning is from Moralis
---

feat: Specifiy warning/error source

---

packages/evmApi/src/EvmApi.ts
packages/evmApi/src/resolvers/native/index.ts
packages/evmApi/src/resolvers/resolve/index.ts
packages/evmApi/src/resolvers/resolve/resolveAddress.ts
packages/test-app-all/src/EvmApi.tsx

feat(evmApi): resolve api for resolveAddress endpoint

---

src/Chains.js
types/index.d.ts

---
about: Adds Cronos support for the SDK
---

Add support for cronos

---

packages/integration/mockRequests/evmApi/getAllTokenIds.ts
packages/integration/mockRequests/mockRequests.ts
packages/integration/test/evmApi/getAllTokenIds.test.ts

---
name: Fetch and transform token.getAllTokenIds
about: Test to get all token Ids
---
Users can get all token Ids by passing an address

test(evmApi): testing get all token Ids

---

packages/integration/mockRequests/evmApi/getContractNFTTransfers.ts
packages/integration/mockRequests/mockRequests.ts
packages/integration/test/evmApi/getContractNFTTransfers.test.ts

---
name: Fetch and transform token.getContractNFTTransfers
about: Test to get contract NFT transfers.
---
User can get the contract NFT transfers by passing an address.

test(evmApi): testing get contract for NFT transfers

---

packages/integration/mockRequests/evmApi/searchNFTs.ts
packages/integration/mockRequests/mockRequests.ts
packages/integration/test/evmApi/searchNFTs.test.ts

---
name: Fetch and transform token.searchNFTs
about: Test to search NFTs
---
Users can search NFTs.

test(evmApi): testing search NFTs

---

packages/integration/mockRequests/evmApi/getTokenAddressTransfers.ts
packages/integration/mockRequests/mockRequests.ts
packages/integration/test/evmApi/getTokenAddressTransfers.test.ts

---
name: Fetch and transform token.getTokenAddressTransfers
---
User can get token address transfers by passing the address of an account.

test(evmApi): testing get token address transfers

---

packages/integration/mockRequests/evmApi/getWalletTokenIdTransfers.ts
packages/integration/mockRequests/mockRequests.ts
packages/integration/test/evmApi/getWalletTokenIdTransfers.test.ts

---
name: Fetch and transform token.getWalletTokenIdTransfers
about: Test to get wallet token Id transfers.
---
User can get wallet token Id transfers by passing an address.

test(evmApi): testing get wallet token Id transfers

---

packages/core/src/dataTypes/EvmAddress.ts
packages/core/src/dataTypes/EvmChain.ts
packages/core/src/dataTypes/EvmNative.ts
packages/core/src/dataTypes/EvmTransaction/EvmTransaction.ts
packages/core/src/dataTypes/EvmTransaction/EvmTransactionReceipt.ts
packages/core/src/dataTypes/EvmTransaction/EvmTransactionReceiptTypes.ts
packages/core/src/dataTypes/EvmTransaction/EvmTransactionResponse.ts
packages/core/src/dataTypes/EvmTransaction/EvmTransactionResponseTypes.ts
packages/core/src/dataTypes/EvmTransaction/EvmTransactionTypes.ts
packages/core/src/dataTypes/EvmTransaction/index.ts
packages/core/src/dataTypes/index.ts
packages/evm/src/MoralisEvm.ts
packages/evm/src/chainMethods/transferNative.ts
packages/evmApi/src/EvmApiPaginatedResultAdapter.ts
packages/evmApi/src/EvmApiResultAdapter.ts
packages/evmApi/src/resolvers/PaginatedResolver.ts
packages/evmApi/src/resolvers/Resolver.ts
packages/evmApi/src/resolvers/account/getTokenBalances.ts
packages/evmApi/src/resolvers/account/getTransactions.ts
packages/evmApi/src/resolvers/native/getTransaction.ts
packages/evmApi/src/resolvers/token/getTokenMetadata.ts

---
---
- Split up and cleanup files based on EvmTransactions
- Add docs for evm transaction properties
- Improve .equals functions for evm transactions and make more consistent
- Fix todo where we pass chain: 1, for all transaction responses in the api. Now we use the 'chain' param to supply the correct chain to the evnTransactions

feat: improve Transaction datatype and

---

packages/integration/mockRequests/evmApi/endpointWeights.ts
packages/integration/mockRequests/mockRequests.ts
packages/integration/test/evmApi/endpointWeights.test.ts

---
name: Fetch and transform info.endpointWeights
about: Test to get info on endpoint weights.
---
Users can get info on endpoint weight

test(evmApi): testing endpoint weight

---

packages/integration/mockRequests/evmApi/getNFTMetadata.ts
packages/integration/mockRequests/mockRequests.ts
packages/integration/test/evmApi/getNFTMetadata.test.ts

---
name: Fetch and transform token.getNFTMetadata
about: Test to get NFT metadata.
---
Users can get NFT metadata by passing an address.

test(evmApi): testing get NFT metadata

---

demos/test-app-all/src/EvmApi.tsx
packages/integration/mockRequests/evmApi/getBlock.ts
packages/integration/mockRequests/mockRequests.ts
packages/integration/test/evmApi/getBlock.test.ts

---
name: Fetch and transform native.getBlock
about: Test to get block.
---

test(evmApi): testing get block

---

packages/integration/mockRequests/evmApi/getTransaction.ts
packages/integration/mockRequests/mockRequests.ts
packages/integration/test/evmApi/getTransaction.test.ts

---
name: Fetch and transform native.getTransaction
about: Test to get transaction
---
User can get transaction by passing a hash

test(evmApi): testing get transaction

---

demos/test-app-all/src/EvmApi.tsx
packages/core/src/controllers/RequestController.ts
packages/evmApi/src/EvmApi.ts
packages/evmApi/src/resolvers/Resolver.ts
packages/evmApi/src/resolvers/token/index.ts
packages/evmApi/src/resolvers/token/syncNFTContract.ts

---
name: syncNFTContract
about: Fetch and transform token.syncNFTContract
---

handle put request and resolve syncNFTContract

---

packages/integration/mockRequests/evmApi/getNFTOwners.ts
packages/integration/mockRequests/mockRequests.ts
packages/integration/test/evmApi/getNFTOwners.test.ts

---
name: Fetch and transform token.getNFTOwners
about: Testing get NFT owners.
---

test(evmApi): testing get NFT owners

---

packages/integration/mockRequests/evmApi/getTokenIdOwners.ts
packages/integration/mockRequests/mockRequests.ts
packages/integration/test/evmApi/getTokenIdOwners.test.ts

---
name: Fetch and transform token.getTokenIdOwners
about: Test to get token Id owners
---

test(evmApi): testing get token id owners

---

packages/server/src/MoralisServer.ts

feat: get current user

---

packages/integration/mockRequests/evmApi/getTokenMetadata.ts
packages/integration/mockRequests/mockRequests.ts
packages/integration/test/evmApi/getTokenMetadata.test.ts

---
name: Fetch and transform token.getTokenMetadata
about: Test to get token metadata
---

test(evmApi): testing get token metadata

---

packages/evmApi/src/EvmApiResultAdapter.ts
packages/integration/test/evmApi/getAllTokenIds.test.ts
packages/integration/test/evmApi/getBlock.test.ts
packages/integration/test/evmApi/getContractNFTTransfers.test.ts
packages/integration/test/evmApi/getDateToBlock.test.ts
packages/integration/test/evmApi/getLogsByAddress.test.ts
packages/integration/test/evmApi/getNFTLowestPrice.test.ts
packages/integration/test/evmApi/getNFTMetadata.test.ts
packages/integration/test/evmApi/getNFTOwners.test.ts
packages/integration/test/evmApi/getNFTTrades.test.ts
packages/integration/test/evmApi/getNFTTransfers.test.ts
packages/integration/test/evmApi/getNFTTransfersByBlock.test.ts
packages/integration/test/evmApi/getNFTTransfersFromToBlock.test.ts
packages/integration/test/evmApi/getNFTs.test.ts
packages/integration/test/evmApi/getNFTsForContract.test.ts
packages/integration/test/evmApi/getPairReserves.test.ts
packages/integration/test/evmApi/getTokenAddressTransfers.test.ts
packages/integration/test/evmApi/getTokenAllowance.test.ts
packages/integration/test/evmApi/getTokenIdMetadata.test.ts
packages/integration/test/evmApi/getTokenIdOwners.test.ts
packages/integration/test/evmApi/getTokenMetadata.test.ts
packages/integration/test/evmApi/getTokenMetadataBySymbol.test.ts
packages/integration/test/evmApi/getTokenTransfers.test.ts
packages/integration/test/evmApi/getTransaction.test.ts
packages/integration/test/evmApi/getTransactions.test.ts
packages/integration/test/evmApi/getWalletTokenIdTransfers.test.ts
packages/integration/test/evmApi/resolveAddress.test.ts
packages/integration/test/evmApi/resolveDomain.test.ts
packages/integration/test/evmApi/searchNFTs.test.ts
packages/integration/test/evmApi/web3ApiVersion.test.ts

---
---
Rename legacy to raw for unformatted apiResults, as it is more descriptive.

feat: better naming for unformatted api result

---

demos/test-app-all/src/App.tsx
demos/test-app-all/src/EvmApi.tsx
packages/evmApi/src/EvmApi.ts
packages/evmApi/src/resolvers/native/getContractEvents.ts
packages/evmApi/src/resolvers/native/index.ts

resolve getContractEvent endpoint

---

packages/server/src/AuthMethods/handleLogout.ts
packages/server/src/Authentication/Authentication.ts

---
---
Clear cashed server data on logout

feat: clear server data on logout

---

packages/evmApi/src/utils/getNextParams.ts

clean the getNextParams function
---
---

perf(evmaapi): getnextparams

---

package-lock.json
scripts/genWeb3API.js
src/MoralisWeb3Api.js

check if result is available before handling pagination options
---
name: Web3Api pagination options fix
---

fix(web3api): paginated result fix

---

package.json
yarn.lock

---
---
Eslint test would fail because of version mismatch with typescript-eslint
Add typescript-eslint as dev dependency

Fix eslint rules

---

.eslintrc.js
package.json
yarn.lock

---
---
Force use of curly brackets when using if-else / try-catch etc.

Force use of curly brackets

---

packages/core/src/controllers/AxiosRetry.test.ts

---
name: Restore AxiosRetry tests
---

test: restore AxiosRetry tests.

---

packages/integration/mockRequests/evmApi/uploadFolder.ts
packages/integration/mockRequests/mockRequests.ts
packages/integration/test/evmApi/uploadFolder.test.ts

---
name: Fetch and transform storage.uploadFolder
about: Testing upload folder
---

test(evmApi): testing upload folder

---

.changeset/curly-boats-stare.md
packages/evmApi/src/resolvers/token/syncNFTContract.ts

refactor(evmApi): syncNFTcontract update

---

packages/core/src/test/EvmTransactionLog.test.ts

---
name: 'evmtransactionlog TEST'
---

test(core): test coverage for evmtransactionlog datatype

---

packages/core/src/State/MoralisState.test.ts
packages/core/src/State/MoralisState.ts
packages/evm/src/Connection/Connection.ts

---
name: unit tests for MoralisState.
---

test(core): unit tests for MoralisState.

---

packages/integration/mockRequests/evmApi/getPairAddress.ts
packages/integration/mockRequests/mockRequests.ts
packages/integration/test/evmApi/getPairAddress.test.ts

---
name: Fetch and transform defi.getPairAddress
about: Testing get pair address
---

test(evmApi): testing and resolving get pair address

---

packages/core/src/Error/MoralisError.spec.ts
packages/core/src/Error/MoralisError.ts
packages/core/src/Error/isMoralisError.spec.ts

---
name: MoralisError unit tests.
---

test(core): MoralisError unit tests.

---

packages/core/src/dataTypes/EvmNative.test.ts
packages/core/src/dataTypes/EvmNative.ts

---
name: unit tests for EvmNative.
---

test: unit tests for EvmNative.

---

packages/core/src/dataTypes/EvmTransaction/EvmTransactionReceipt.ts
packages/core/src/test/EvmTransactionReceipt.test.ts

test(evmTransactionReceipt): test coverate for EvmTransactionReceipt

---

scripts/genWeb3API.js
src/MoralisWeb3Api.js

---
name: 'Cursor pagination fix'
---

remove page check when using cursor pagination

---

tsconfig.package.json

fix .d.ts files

---

jest.config.js
packages/integration/mockRequests/config.ts
packages/integration/mockRequests/mockRequestSol.ts
packages/integration/mockRequests/solApi/getBalance.ts
packages/integration/test/solApi/getBalance.test.ts
packages/integration/test/solApi/setup.ts

---
name: Fetch and transform account.balance
about: Testing get balance
---

test(solanaApi): testing get balance

---

src/Parse.js

fix casing for tracking keys

---

.changeset/quiet-fans-lay.md
packages/core/package.json

---
---
Fix typed emitter depenendency

fix: typed-emitter dependency

---

demos/test-node/src/main.ts
packages/apiUtils/src/resolvers/EndpointResolver.ts
packages/apiUtils/src/resolvers/Endpoints.ts
packages/apiUtils/src/resolvers/PaginatedEndpointResolver.ts
packages/apiUtils/src/resolvers/index.ts
packages/evmApi/src/EvmApi.ts
packages/solApi/src/MoralisSolApi.ts
packages/solApi/src/resolvers/account/getBalance.ts
packages/solApi/src/resolvers/account/getNFTs.ts
packages/solApi/src/resolvers/account/getPortfolio.ts
packages/solApi/src/resolvers/account/getSPL.ts
packages/solApi/src/resolvers/nft/getNFTMetadata.ts

---
name: endpoint descriptors.
---

feat(api): endpoint descriptors.

---

.changeset/red-crews-sniff.md
packages/evmApi/src/resolvers/account/getNFTs.ts

---
---
Add `amount` to getNfts endpoint

fix: add amount in getNfts endpoint

---

.changeset/lazy-ducks-run.md
.changeset/shaggy-maps-appear.md
packages/evmApi/src/resolvers/account/getNFTsForContract.ts
packages/evmApi/src/resolvers/account/getTokenBalances.ts
packages/evmApi/src/resolvers/native/getBlock.ts
packages/evmApi/src/resolvers/native/getLogsByAddress.ts
packages/evmApi/src/resolvers/native/getTransaction.ts
packages/evmApi/src/resolvers/token/getNFTOwners.ts
packages/evmApi/src/resolvers/token/getNFTTrades.ts
packages/evmApi/src/resolvers/token/getTokenAddressTransfers.ts
packages/evmApi/src/resolvers/token/getTokenMetadata.ts
packages/evmApi/src/resolvers/token/getTokenMetadataBySymbol.ts
packages/evmUtils/src/dataTypes/Erc20Value/Erc20Value.ts

Fix evm api arrays

---

demos/demo-supabase-auth/public/index.html
demos/demo-supabase-auth/public/script.js
demos/demo-supabase-auth/src/auth/authService.ts

correct stored id and add anon request

---

.changeset/soft-hairs-applaud.md
packages/evmApi/src/resolvers/account/getNFTTransfers.ts

---
---
Fix  tokenAddress value

fix: tokenAddress in getNFTTransfers

---

packages/core/.gitignore
packages/core/src/version.ts

---
---
Remove version.ts from git control, as it only should be generated in the the build step

chore: remove version from git

---

.changeset/friendly-tips-eat.md
packages/core/src/utils/maybe.ts
packages/evmUtils/src/dataTypes/Erc20/Erc20.ts
packages/evmUtils/src/dataTypes/EvmEvent/EvmEvent.ts
packages/evmUtils/src/dataTypes/EvmEvent/types.ts
packages/evmUtils/src/dataTypes/EvmNft/types.ts
packages/evmUtils/src/dataTypes/EvmNftMetadata/types.ts
packages/evmUtils/src/dataTypes/EvmTransaction/EvmTransaction.ts

---
name: corrected TypeScript definition of the `maybe()` method
---

fix: corrected TypeScript definition of maybe() method

---

README.md

---
name: back-end only warning.
---

back-end only warning.

---

demos/supabase-auth/src/auth/authService.ts

---
---
Better domain name for examples

chore: rename domain in examples

---

.changeset/calm-birds-buy.md
packages/evmUtils/src/dataTypes/EvmChain/EvmChain.ts

---
---
Fix chainId for avalanche from 43113 to 43114

fix: avalanche chainId

---

.gitignore
.vscode/extensions.json
.vscode/settings.json
packages/solUtils/src/dataTypes/SolAddress/SolAddress.ts
packages/solUtils/src/dataTypes/SolNetwork/SolNetwork.test.ts
packages/solUtils/src/dataTypes/SolNetwork/SolNetwork.ts

---
name: ['Pull request'
about: A new pull request](docs: SolNetwork.)
---

docs: SolNetwork.

---

.changeset/dull-pianos-compare.md
packages/apiUtils/src/resolvers/EndpointParamsReader.ts

---
name: fixed creating a body of POST requests.
---

fix: fixed creating a body of POST requests.

---

.changeset/funny-clocks-grow.md

fixed changeset.

---

packages/core/src/dataTypes/BigNumber/BigNumber.ts
packages/core/src/dataTypes/BigNumber/BigNumberParser.ts
packages/evmUtils/src/dataTypes/EvmNative/EvmNative.ts

technical documentation for EvmNative datatype
---
---

docs: EvmNative

---

packages/solUtils/src/dataTypes/SolNative/SolNative.ts

technical docs for solana native datatype
---
---

docs: SolNative

---

packages/evmUtils/src/dataTypes/EvmBlock/EvmBlock.ts
packages/evmUtils/src/dataTypes/EvmBlock/types.ts

technical docs for evm block datatype
---
---

docs: EvmBlock

---

packages/evmUtils/src/dataTypes/Erc20Transfer/Erc20Transfer.ts
packages/evmUtils/src/dataTypes/Erc20Transfer/types.ts

technical docs for erc20 transfer datatype
---
---

docs: Erc20Transfer

---

packages/evmUtils/src/dataTypes/EvmEvent/EvmEvent.ts
packages/evmUtils/src/dataTypes/EvmEvent/types.ts

docs(EvmEvent): technical docs for evmEvent datatype

---

packages/evmUtils/src/dataTypes/EvmNftTrade/EvmNftTrade.ts
packages/evmUtils/src/dataTypes/EvmNftTrade/types.ts

technical docs for nft trade datatype
---
---

docs: EvmNftTrade

---

packages/evmUtils/src/dataTypes/EvmNftMetadata/EvmNftMetadata.ts
packages/evmUtils/src/dataTypes/EvmNftMetadata/types.ts

technical docs for nft metadata
---
---

docs: EvmNftMetadata

---

README.md
demos/cli/src/EvmApi.ts
demos/cli/src/main.ts
demos/firebase-proxy/functions/src/index.ts
demos/firebase-proxy/hosting/index.html
demos/firebase-proxy/hosting/main.js

---
name: upgrade api method names for demos.
---

upgrade api method names for demos.

---

packages/auth/src/MoralisAuth.ts

change base url for auth api calls
---
---

refactor: AuthAPI

---

demos/parse-server/public/index.html
demos/parse-server/public/script.js
demos/parse-server/src/auth/MoralisAuthAdapter.ts
demos/parse-server/src/auth/authService.ts

add solana authentication example to demo
---
---

feat: sol-auth

---

packages/streams/package.json
packages/streams/src/MoralisStreams.ts
packages/streams/src/methods/logDecoder.test.ts
packages/streams/src/methods/logDecoder.ts
packages/streams/src/methods/logParser.test.ts
packages/streams/src/methods/logParser.ts
packages/streams/src/utils/logDecoderUtils.ts

add tests and use moralis errors

---

packages/streams/src/methods/logParser.ts
packages/streams/src/utils/logDecoderUtils.ts

perf(logParser): check input indexed when compiling decode data

---

.changeset/lazy-lies-hide.md
packages/streams/src/MoralisStreams.ts

fix: provide type to parsedLogs

---

.changeset/stale-walls-travel.md
packages/streams/package.json
yarn.lock

Update stream types

---

.changeset/wild-islands-fail.md
packages/client/firebaseEvmAuth/src/signInWithMoralis.ts

---
name: change approach for reading an address of EVM wallet.
---

fix: change approach to reading address of EVM wallet.

---

.changeset/beige-trains-study.md
packages/client/firebaseEvmAuth/src/signInWithMoralis.ts

---
name: fixed problem with connection to MetaMask.
---

fix: fixed problem with connection to MetaMask.

---

.changeset/late-ladybugs-rescue.md
demos/cli/package.json
demos/express-proxy/package.json
demos/firebase-auth/functions/package.json
demos/firebase-proxy/functions/package.json
demos/moralis-stream/package.json
demos/parse-server-migration/package.json
demos/parse-server/package.json
demos/supabase-auth/package.json
packages/eslintConfig/README.md
packages/eslintConfig/package.json

---
---
Updated peer dependencies of eslint-config

Update eslint dependencies

---

packages/integration/mockRequests/evmApi/getTokenPrice.ts
packages/integration/test/evmApi/getTokenPrice.test.ts

---
name: refactor getTokenPrice tests.
---

refactor getTokenPrice tests.

---

scripts/buildDemoDocs.js

---
---
Fix building of docs, now that `valid-dependencies` is part of the `/demos` folder

ci: fix building of docs

---

.changeset/modern-mails-cover.md
packages/streams/package.json
yarn.lock

---
---
Update streams api types package

fix: update streams api types

---

.changeset/wicked-badgers-pretend.md
packages/apiUtils/src/resolvers/EndpointResolver.ts
packages/core/src/controllers/RequestController/RequestController.ts
packages/integration/mockRequests/streamApi/deleteAddress.ts
packages/integration/test/core/requestController/requestControllerDelete.test.ts
packages/integration/test/core/requestController/requestControllerPost.test.ts
packages/integration/test/core/requestController/requestControllerPut.test.ts
packages/integration/test/streamApi/deleteAddress.test.ts

---
---
- Send body in delete requests
- Add integration tests for RequestController
- Update tests for deleteAddress to account for checking passed params

fix: send body in delete requests

---

demos/firebase-auth-ext/README.md

---
name: update readme.md for firebase auth demo.
---

update readme.md for firebase auth demo.

---

packages/streams/src/methods/verifySignature.ts

---
name: fixed wrong body type for verifySignature method.
---

fixed wrong body type for verifySignature method.

---

README.md
demos/parse-server-migration-react-client/README.md

---
name: 'Typo on two readme files'
---
This is a simple PR resolving a typo issue

docs: typo on readme files

---

demos/supabase-auth/.env.example

Env variable wasn't matching with the Supabase auth

---

.changeset/grumpy-apes-bathe.md
packages/moralis/package.json
packages/streams/package.json

fix: streams-typings

---

demos/parse-server/public/script.js
demos/parse-server/src/auth/authService.ts

---
name: header fix for parse-server.
---

header fix for parse-server.

---

.github/workflows/main.yml

---
---
Re-add solana utils test coverage

test: re-add solUtils test coverage

---

packages/apiUtils/src/resolvers2/OperationRequestBuilder.test.ts
packages/common/core/src/operations/Operation.ts
packages/common/evmUtils/src/operations/operations.test.ts
packages/common/evmUtils/src/operations/token/getWalletTokenTransfersOperation.test.ts
packages/common/evmUtils/src/operations/token/getWalletTokenTransfersOperation.ts
packages/common/evmUtils/src/operations/utils/runContractFunctionOperation.test.ts
packages/common/evmUtils/src/operations/utils/runContractFunctionOperation.ts
packages/common/solUtils/src/operations/account/getBalanceOperation.test.ts
packages/common/solUtils/src/operations/account/getBalanceOperation.ts
packages/common/solUtils/src/operations/account/getNFTsOperation.test.ts
packages/common/solUtils/src/operations/account/getNFTsOperation.ts
packages/common/solUtils/src/operations/account/getPortfolioOperation.test.ts
packages/common/solUtils/src/operations/account/getPortfolioOperation.ts
packages/common/solUtils/src/operations/account/getSPLOperation.test.ts
packages/common/solUtils/src/operations/account/getSPLOperation.ts
packages/common/solUtils/src/operations/nft/getNFTMetadataOperation.test.ts
packages/common/solUtils/src/operations/nft/getNFTMetadataOperation.ts
packages/common/solUtils/src/operations/operations.test.ts
packages/common/solUtils/src/operations/token/getTokenPriceOperation.test.ts
packages/common/solUtils/src/operations/token/getTokenPriceOperation.ts

---
name: add `id` to Operation interface.
---

add id to Operation interface.

---

packages/apiUtils/src/resolvers2/NullableOperationResolver.ts
packages/apiUtils/src/resolvers2/OperationRequestBuilder.test.ts
packages/apiUtils/src/resolvers2/OperationRequestBuilder.ts
packages/apiUtils/src/resolvers2/PaginatedOperationResolver.ts
packages/common/core/src/operations/Operation.ts
packages/common/core/src/operations/PaginatedOperation.ts
packages/common/evmUtils/src/operations/token/getWalletTokenTransfersOperation.ts

---
name: mandatory properties for Operation interface.
---

mandatory properties for Operation interface.

---

.changeset/healthy-adults-join.md
packages/streams/package.json

---
name: add missing dependency to the streams package.
---

add missing dependency to the streams package.

---

.github/workflows/main.yml
packages/apiUtils/package.json
packages/client/firebaseApiUtils/package.json
packages/client/firebaseAuthUtils/package.json
packages/client/firebaseEvmApi/package.json
packages/client/firebaseEvmAuth/package.json
packages/client/firebaseSolApi/package.json
packages/client/firebaseSolAuth/package.json
packages/common/evmUtils/package.json
packages/common/streamsUtils/package.json
scripts/findMissingDependencies.js
yarn.lock

---
name: missing dependencies validator.
---

missing dependencies validator.

---

packages/common/evmUtils/src/operations/events/getContractLogsOperation.ts

---
name: fix deserializeResponse for getContractLogOperation
---

fix: deserializeResponse for getContractLog

---

.changeset/silver-laws-heal.md
packages/evmApi/src/resolvers/events/getContractLogs.ts

---
---
Fix potential missing chainId

fix: account for missing chain

---

packages/evmApi/integration/mocks/endpoints/getBlock.ts
packages/evmApi/integration/mocks/endpoints/getDateToBlock.ts
packages/evmApi/integration/mocks/mockServer.ts
packages/evmApi/integration/test/getBlock.test.ts
packages/evmApi/integration/test/getDateToBlock.test.ts

---
name: Test
about: scenario based tests for evm blocks
---

chore(evm): scenario based tests for evm blocks

---

packages/evmApi/integration/mocks/endpoints/getPairAddress.ts
packages/evmApi/integration/mocks/endpoints/getPairReserves.ts
packages/evmApi/integration/mocks/mockServer.ts
packages/evmApi/integration/test/getPairAddress.test.ts
packages/evmApi/integration/test/getPairReserves.test.ts
packages/evmApi/src/resolvers/defi/getPairAddress.ts

---
name: EVM defi integration tests.
---

EVM defi integration tests.

---

packages/evmApi/integration/mocks/endpoints/resolveAddress.ts
packages/evmApi/integration/mocks/endpoints/resolveDomain.ts
packages/evmApi/integration/mocks/mockServer.ts
packages/evmApi/integration/test/resolveAddress.test.ts
packages/evmApi/integration/test/resolveDomain.test.ts

---
about: scenario based tests for resolve DNS endpoints
---

chore(evm): scenario based tests for resolve DNS endpoints

---

packages/evmApi/integration/mocks/endpoints/endpointWeights.ts
packages/evmApi/integration/mocks/endpoints/runContractFunction.ts
packages/evmApi/integration/mocks/endpoints/web3ApiVersion.ts
packages/evmApi/integration/mocks/mockServer.ts
packages/evmApi/integration/test/endpointWeights.test.ts
packages/evmApi/integration/test/runContractFunction.test.ts
packages/evmApi/integration/test/web3ApiVersion.test.ts
packages/evmApi/src/resolvers/utils/runContractFunction.ts

---
name: EVM utils integration tests.
---

EVM utils integration tests.

---

.changeset/twelve-cows-film.md
packages/common/core/src/controllers/RequestController/RequestController.ts

fix: change HTTP timeout to 20 seconds

---

packages/evmUtils/README.md
packages/evmUtils/package.json
packages/evmUtils/src/index.ts
packages/evmUtils/tsconfig.build.json
packages/evmUtils/tsconfig.json
packages/solUtils/README.md
packages/solUtils/package.json
packages/solUtils/src/index.ts
packages/solUtils/tsconfig.build.json
packages/solUtils/tsconfig.json

---
name: revert depreciated evm-utils & sol-utils packages.
---

revert depreciated evm-utils & sol-utils packages.

---

packages/apiUtils/src/resolvers2/OperationRequestBuilder.ts

---
about: add product tracking for new resolver
---

feat: add product tracking for new resolver

---

packages/codegen/src/next/generators/readme/ReadmeGenerator.ts
packages/codegen/src/next/generators/readme/templates/README.md.hbs
packages/next/README.md
packages/next/package.json

---
about: Polishing README for NextJS package
---

@moralisweb3/next readme improvements

---

.github/workflows/release.yml

---
name: disable releasing for alpha & beta branches.
---

disable releasing for alpha & beta branches.

---

.changeset/shy-cherries-end.md
.changeset/soft-boats-collect.md
packages/common/evmUtils/src/dataTypes/EvmChain/EvmChain.ts
packages/common/evmUtils/src/operations/openapi.ts

---
name: added the ARBITRUM network to EvmChain.
---

added the ARBITRUM network to EvmChain.

---

.changeset/dry-lobsters-nail.md
packages/streams/src/mapping/logs-processor/LogParser.test.ts
packages/streams/src/mapping/logs-processor/LogParser.ts
packages/streams/src/methods/bulkLogParser.test.ts

---
name: improved log parser.
---

improved log parser.

---

packages/next/src/auth/MoralisNextAuthProvider.ts

---
---
Added an id for MoralisNextAuthProvider, so developers now can combine it with another `CredentialsProvider` in Next-Auth authorisation

Added id for MoralisNextAuthProvider

---

demos/nextjs/app/components/modules/Authentication/Authentication.tsx
packages/create-moralis-dapp/src/generators/next/template/app/components/modules/Authentication/Authentication.tsx

Replaced signIn params for NextJS 

---

.changeset/rare-teachers-hide.md
demos/express-proxy/.env.example
demos/express-proxy/public/script.js
demos/express-proxy/src/middlewares/errorHandler.ts
demos/nextjs/package.json
demos/parse-server-migration-react-client/package.json
demos/parse-server-migration/package.json
demos/parse-server/src/middlewares/errorHandler.ts
packages/apiUtils/package.json
packages/common/core/package.json
packages/create-moralis-dapp/package.json
packages/create-moralis-dapp/src/generators/next/template/package.json.tmpl
packages/next/package.json
yarn.lock

---
name: updated axios dependency to 1.2.x.
---

feat: updated axios dependency to 1.2.x.

---

.changeset/cyan-insects-leave.md
demos/nextjs/app/components/modules/Authentication/Authentication.tsx
packages/next/src/auth/MoralisNextAuthProvider.ts

---
about: MoralisNextAuthProvider improve errors handling
---

MoralisNextAuthProvider improve errors handling

---

.changeset/neat-plums-marry.md
packages/next/src/hooks/resolvers/useResolver.ts
packages/next/src/hooks/resolvers/useResolverPaginated.ts

Fix: @moralisweb3/next rerenders when use datatypes

---

demos/parse-server-migration/src/auth/authService.ts

---
name: fixed calculation of expiration time for parse-server-migration demo.
---

fix: fixed calculation of expiration time for parse-server-migration demo.

---

demos/supabase-auth/README.md
demos/supabase-auth/public/script.js
demos/supabase-auth/src/auth/authService.ts
package-lock.json

---
name: 'Fix Supabase Demo authentication'
about: This PR fixes the authentication config in Supabase Demo
---

fix: supabase demo authentication

---

demos/parse-server-migration-react-client/package.json
demos/parse-server-migration-react-client/src/views/Nfts.tsx
demos/parse-server-migration/scripts/generateEvmApiCloud.ts
demos/parse-server-migration/scripts/generateSolApiCloud.ts
demos/parse-server-migration/scripts/types/Endpoint.ts
demos/parse-server-migration/scripts/utils/generateApiCloudCode.ts
demos/parse-server-migration/scripts/utils/prepareSwaggerForApi.ts
demos/parse-server-migration/src/cloud/generated/evmApi.ts
demos/parse-server-migration/src/cloud/generated/solApi.ts
demos/parse-server-migration/src/cloud/upgradeRequest.ts
yarn.lock

---
name: added upgradeRequest method, that upgrades v1 request to v2.
---

fix: added upgradeRequest method, that upgrades v1 request to v2.

---

demos/parse-server-migration/scripts/utils/generateApiCloudCode.ts
demos/parse-server-migration/src/cloud/generated/evmApi.ts
demos/parse-server-migration/src/cloud/generated/solApi.ts

---
name: rename arguments for parse-server-migration.
---

fix: rename arguments for parse-server-migration.

---

demos/parse-server-migration-react-client/src/views/Home.tsx
demos/parse-server-migration/scripts/utils/generateApiCloudCode.ts
demos/parse-server-migration/src/cloud/generated/evmApi.ts
demos/parse-server-migration/src/cloud/generated/solApi.ts
demos/parse-server-migration/src/cloud/upgradeRequest.ts

---
name: fix: upgrade requests from v1 to v2.
---

fix: upgrade requests from v1 to v2.

---

.prettierignore
.yarnrc.yml
demos/parse-server-migration/package.json
demos/parse-server/package.json
yarn.lock

---
---
Outdated parse-server dependency with a mongodb security issue
- Update parse-server dependency
- add update-interactive plugin for yarn

fix: update parse-server dependency

---

demos/firebase-auth-ext/hosting/package.json
demos/nextjs/package.json
demos/parse-server-migration-react-client/package.json
packages/client/firebaseEvmAuth/package.json
packages/common/evmUtils/package.json
packages/streams/package.json
packages/streams/src/mapping/common/Sha256.ts
packages/streams/src/mapping/logs-processor/LogDocumentBuilder.test.ts
packages/streams/src/mapping/logs-processor/LogDocumentValueFormatter.test.ts
packages/streams/src/mapping/logs-processor/LogDocumentValueFormatter.ts
packages/streams/src/mapping/logs-processor/LogParser.test.ts
packages/streams/src/mapping/logs-processor/LogParser.ts
yarn.lock

---
---
- Update ethers dependencies
- Remove direct dependency in our main packages, and changed it to the imports from ethersproject subpackages

fix: update ethers dependencies

---

demos/supabase-auth/package.json
yarn.lock

---
---
Update uuid dependency

fix: update uuid dependency

---

.changeset/healthy-coins-unite.md
packages/apiUtils/src/resolvers2/OperationRequestBuilder.test.ts
packages/apiUtils/src/resolvers2/OperationRequestBuilder.ts
packages/apiUtils/src/resolvers2/getCommonHeaders.ts
packages/apiUtils/src/resolvers2/getSdkDatailsHeaders.ts
packages/apiUtils/src/resolvers2/getSdkDetailsHeaders.ts
packages/next/src/MoralisNextApi/MoralisNextApi.ts
packages/react/src/context/MoralisProvider.tsx

Seperate sdk tracking

---

.github/workflows/main.yml
packages/create-moralis-dapp/react-vite/src/ReactViteFileGenerator/ReactViteFileGenerator.ts

fix: build after refactor cmd

---

packages/apiUtils/src/resolvers2/getSdkDetailsHeaders.ts
packages/common/core/src/controllers/AxiosRetry.ts
packages/common/core/src/utils/noop.test.ts
packages/common/core/src/utils/noop.ts

fix: remove process dependency

---

packages/aptosApi/integration/mocks/endpoints/blocks.getBlockByHeight.ts
packages/aptosApi/integration/mocks/endpoints/transactions.getTransactions.ts
packages/aptosApi/integration/mocks/endpoints/transactions.simulateTransaction.ts
packages/aptosApi/integration/mocks/mockServer.ts
packages/aptosApi/integration/tests/transactions.getTransactions.test.ts
packages/aptosApi/integration/tests/transactions.simulateTransaction.test.ts

---
name: test: 2 more aptos integration tests.
---

test: 2 more aptos integration tests.

---

.changeset/eight-owls-eat.md

fix: changeset

---

.github/stale.yml

ci: add stalebot

---

CONTRIBUTING.md
packages/create-moralis-dapp/create-moralis-dapp/package.json
packages/create-moralis-dapp/create-moralis-dapp/src/CMDGenerator.ts
packages/create-moralis-dapp/express/src/ExpressAppInquirer.ts
packages/create-moralis-dapp/next/src/NextAppInquirer.ts
packages/create-moralis-dapp/react-cra/src/ReactCraAppInquirer.ts
packages/create-moralis-dapp/react-vite/src/ReactViteAppInquirer.ts
packages/create-moralis-dapp/toolkit/package.json
packages/create-moralis-dapp/toolkit/src/Inquirer.ts
packages/create-moralis-dapp/toolkit/src/TemplateProcessor.ts
yarn.lock

---
---
`Inquirer` is missing some useful features in comparison to `prompts`, such as:
1. No `description` option
2. Emoji doesn't change from ? to √ after the question was answered.
3. Better interactivity and better customizability

[CLI UX v1] Switched "inquirer" to "prompts" library

---

.changeset/ninety-keys-camp.md
packages/common/aptosUtils/src/dataTypes/AptosAddress/AptosAddress.test.ts
packages/common/aptosUtils/src/dataTypes/AptosAddress/AptosAddress.ts

---
name: shortening aptos address.
---

feat: shortening aptos address.

---

.changeset/four-eels-poke.md
.prettierignore
demos/firebase-streams-ext/functions/scripts/batch-triggers.json
demos/firebase-streams-ext/functions/scripts/send-test-batches.js
packages/moralis/package.json
packages/streams/package.json
packages/streams/src/mapping/common/TriggerItemsBuilder.test.ts
packages/streams/src/mapping/common/TriggerItemsBuilder.ts
packages/streams/src/mapping/erc20-approvals-processor/Erc20ApprovalDocumentBuilder.test.ts
packages/streams/src/mapping/erc20-approvals-processor/Erc20ApprovalDocumentBuilder.ts
packages/streams/src/mapping/erc20-transfers-processor/Erc20TransferDocumentBuilder.test.ts
packages/streams/src/mapping/erc20-transfers-processor/Erc20TransferDocumentBuilder.ts
packages/streams/src/mapping/logs-processor/LogDocumentBuilder.test.ts
packages/streams/src/mapping/logs-processor/LogDocumentBuilder.ts
packages/streams/src/mapping/nft-transfers-processor/NftTransferDocumentBuilder.test.ts
packages/streams/src/mapping/nft-transfers-processor/NftTransferDocumentBuilder.ts
packages/streams/src/mapping/storage/Update.ts
packages/streams/src/mapping/txs-processor/TxDocumentBuilder.test.ts
packages/streams/src/mapping/txs-processor/TxDocumentBuilder.ts
yarn.lock

---
name: feat: added support for triggers.
---

feat: added support for triggers.

---

packages/codegen/package.json
packages/codegen/src/sdk/generators/readme/ReadmeGenerator.ts
yarn.lock

fix: codegen fixed.

---

packages/codegen/src/next/generators/readme/templates/hook_desc.hbs
packages/codegen/src/react/generators/readme/templates/hook_desc.hbs
packages/next/README.md
packages/react/README.md

NextJS and React packages Readme fix

---

.changeset/fresh-tigers-relax.md
packages/common/streamsUtils/src/dataTypes/EvmStreamResult/EvmStreamResult.mock.ts
packages/common/streamsUtils/src/dataTypes/EvmStreamResult/EvmStreamResult.test.ts
packages/common/streamsUtils/src/dataTypes/EvmStreamResult/EvmStreamResult.ts
packages/common/streamsUtils/src/dataTypes/EvmStreamResult/EvmStreamResultFormatter.ts
packages/common/streamsUtils/src/dataTypes/EvmStreamResult/EvmStreamResultParser.ts
packages/common/streamsUtils/src/dataTypes/EvmStreamResult/types.ts
packages/common/streamsUtils/src/dataTypes/StreamEvmNftTokenApproval/StreamEvmNftTokenApproval.test.ts
packages/common/streamsUtils/src/dataTypes/StreamEvmNftTokenApproval/StreamEvmNftTokenApproval.ts
packages/common/streamsUtils/src/dataTypes/StreamEvmNftTokenApproval/index.ts
packages/common/streamsUtils/src/dataTypes/StreamEvmNftTokenApproval/types.ts
packages/common/streamsUtils/src/dataTypes/index.ts

---
name: added `ntfTokenApprovals` to `EvmStreamResult` class.
---

feat: added `ntfTokenApprovals` to `EvmStreamResult` class.

---

.changeset/tasty-keys-invite.md
packages/next/src/MoralisNextApi/MoralisNextApi.ts
packages/next/src/MoralisNextApi/types.ts

---
---
Removed all configuration options for `MoralisNextApi` except `apiKey` and `authentication`.

🐛 Removed Core configuration for MoralisNextApi

---

.changeset/popular-maps-end.md
packages/apiGenerator/src/generator/GeneratorConfiguration.ts
packages/apiGenerator/src/generator/fileGenerators/codeGenerators/JSDocTypeResolver.spec.ts
packages/apiGenerator/src/generator/fileGenerators/codeGenerators/JSDocTypeResolver.ts
packages/apiGenerator/src/generator/fileGenerators/codeGenerators/TypeCodesGenerator.ts
packages/apiGenerator/src/generator/fileGenerators/codeGenerators/TypeConversionCodeGenerator.spec.ts
packages/apiGenerator/src/generator/fileGenerators/codeGenerators/TypeConversionCodeGenerator.ts
packages/apiGenerator/src/generator/fileGenerators/codeGenerators/ValueMappingCodeGenerator.ts
packages/apiGenerator/src/generator/fileGenerators/resolvers/TypeResolver.ts
packages/common/core/src/dataTypes/BigNumber/BigNumber.ts
packages/common/evmUtils/generator.config.json
packages/common/evmUtils/src/generated/types/EvmTrade.ts
packages/evmApi/integration/test/getNFTTrades.test.ts

---
name: feat: casting to simple types.
---

feat: casting to simple types.

---

.changeset/thirty-monkeys-impress.md
.changeset/violet-baboons-report.md
packages/common/aptosUtils/src/generated/client/abstractClient.ts
packages/common/aptosUtils/src/generated/operations/GetNFTTransfersByIdsOperation.ts
packages/common/aptosUtils/src/generated/types/AptosNFTTransferResponse.ts

---
name: fix: updated broken aptos types.
---

fix: updated broken aptos types.

---

.changeset/chilled-clouds-heal.md
packages/common/evmUtils/scripts/fetch-chaindata.js
packages/common/evmUtils/src/data/chaindata.ts
packages/common/evmUtils/src/dataTypes/EvmChain/EvmChain.test.ts
packages/common/evmUtils/src/dataTypes/EvmChain/EvmChain.ts

---
name: feat: deleted support for cronos testnet and avalanche testnet.
---

feat: deleted support for cronos testnet and avalanche testnet.

---

packages/client/firebaseEvmAuth/package.json
yarn.lock

---
name: feat: update detect provider.
---

feat: update @metamask/detect-provider.

---

.changeset/plenty-insects-refuse.md
packages/common/solUtils/src/operations/token/getTokenPriceOperation.ts
packages/solApi/integration/mocks/endpoints/getTokenPrice.ts
packages/solApi/integration/mocks/mockServer.ts
packages/solApi/integration/test/getTokenPrice.test.ts

---
name: fix: solana native price conversion.
---

fix: solana native price conversion.

---

.changeset/few-humans-breathe.md
demos/express-proxy/src/api/proxyGenerator.ts
demos/parse-server-migration/scripts/utils/generateApiCloudCode.ts
demos/parse-server-migration/src/cloud/generated/evmApi.ts
demos/parse-server-migration/src/cloud/generated/solApi.ts
demos/parse-server/src/api/proxyGenerator.ts
packages/common/evmUtils/src/operations/operations.ts
packages/common/solUtils/src/operations/operations.ts
packages/next/src/MoralisNextApi/Modules.ts

---
name: fix: repaired parse-server-migration.
---

fix: repaired parse-server-migration.

---

.changeset/good-ducks-return.md
packages/common/evmUtils/scripts/fetch-chaindata.js
packages/common/evmUtils/src/data/chaindata.ts
packages/common/evmUtils/src/dataTypes/EvmChain/EvmChain.test.ts
packages/common/evmUtils/src/dataTypes/EvmChain/EvmChain.ts

---
feat: add new chains to EvmChain.
---

feat: add new chains to EvmChain.
