MoralisWeb3/Moralis-JS-SDK

src/MoralisWalletConnectProvider.js
Added option for providing list of wallets for connecting via WC from mobile phone
Example: 
```
let user = await Moralis.authenticate({
provider: "walletconnect",
mobileLinks: [ "rainbow","metamask","argent","trust","imtoken","pillar"  ]
});
```
WC docs: https://docs.walletconnect.org/quick-start/dapps/web3-provider#filter-mobile-linking-options
=> feat: allow provide list of wallets for connecting via WC

package-lock.json, types/generated/web3Api.d.ts, types/index.d.ts
Follow up on this problem: https://forum.moralis.io/t/incorrect-spelling-in-the-file-index-d-ts-in-the-import-of-generated-web3api-d-ts/2638
Two commits, first with changed `index.d.ts` file, second with two files that got changed automatically after running `npm install`. I don't know if I should include the second commit. If the second commit should not be included, just merge only the first commit containing the import path fix in `index.d.ts`. Thanks!
=> Fixed import path of GeneratedWeb3API in index.d.ts

src/MoralisWeb3.js
CHANGELOG: The errors thrown by plugins built using AST are now correctly propagated
=> fix: propagate plugin errors

src/MoralisWeb3.js
---
about: Remove JSON.parse from error propagation
---
The plugins now throws errors that are objects, therefore parsing them throws an error.
Remove JSON.parse() from error propagation.
=> Fix: remove json parser from error propagation

src/MoralisWeb3.js
---
name: 'feature/global_web3objectt'
about: Moralis global web3 provider for web3 methods
---
`Moralis.transfer()` and `Moralis.executeFunction()` enable `Moralis.Web3()` only for metamask.
Instead of using `Moralis.Web3()` each time use:
```
if (!this.ensureWeb3IsInstalled()) throw new Error(ERROR_WEB3_MISSING);
const web3 = this.web3;
```
=> feature: Using this.web3 instead of Moralis.Web3() each time

types/generated/web3Api.d.ts
---
Name: **Update web3Api.d.ts**
About: **Rename eth-defi to ethDefi**
---
Related issue: Projects made on Typescript and Next.js crashed after `npm run build` due to invalid name `eth-defi`.
Changing the `eth-defi` name to `defi`.
=> quickfix: Update web3Api.d.ts

src/MoralisWeb3.js
---
about: Allow SDK to return results from the plugin, even when a `trigger` is present.
---
Whenever a plugin returns a `trigger`, the plugin executes it but does not return the plugin response to the developer.
In some cases, devs need the plugin response.
Enable SDK to return the plugin response even when a trigger is present.
=> Update: Add plugin response propagation

src/MoralisWeb3.js
---
---
Events emmiter shows previos event+new events because it wasn't defined in the function scope.
EventEmitters were moved to functions: `executeFunction` and `transfer`. Every time you call these functions you get clear events cache.
=> fix: events emmiter cleans cache

scripts/genWeb3API.js, scripts/generateWeb3ApiTypes.js, src/MoralisWeb3Api.js, types/generated/web3Api.d.ts
---
Options are not sent to api
---
Passing a chain to the Moralis.Web3Api always sent results for ETH
- [X ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [ X] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [ X] I have made corresponding changes to the documentation
- [ X] I have updated Typescript definitions when needed
The `axios.create` method of axios does not pass the params in the query string leading to inaccurate results.
Use the main axios api to ensure the query params are sent along with the request
=> BUGFIX: missing query params when using api key

src/MoralisWeb3.js, src/Parse.js, src/utils.js
---
about: Notify the user when the SDK is not updated
---
- [] I have made corresponding changes to the documentation
- [] I have updated Typescript definitions when needed
Need a way to notify users when the SDK is not updated.
Match the version in pkg.json with the one returned by the npm registry.
Could not use a better way because browserify breaks if we import package.json
=> feature: check if sdk is updated

types/index.d.ts
---
name: 'Add missing type declaration for signingMessage'
about: missing declaration #135 
---
When trying to update the signingMessage property in the options argument of theMoralis.Web3.authenticate() function, I get the following typescript error:
```
TS2345: Argument of type '{ signingMessage: string; }' is not assignable to parameter of type 'AuthenticationOptions'.
Object literal may only specify known properties, and 'signingMessage' does not exist in type 'AuthenticationOptions'.
```
This is how my imports are implemented on the vue app in question (based off of the vue3-boilerplate project):
```ts
const user: UserModel = await $moralis.Web3.authenticate({
signingMessage: "sign test",
});
```
When I run the above snippet with the $moralis object typed as `any` the code compiles …
=> fix: add missing type declaration

types/index.d.ts
---
name: Missing `sol` type (Moralis Authentication) for Phantom Wallet
about: Add `sol` to `AuthenticationType` (Typescript)
---
Phantom Wallet has been added as an Authentication Method in Moralis SDK, but `type: sol` will get error because it is a missing option in `AuthenticationType`, which will prompt typescript type error issue.
Add `sol` to `AuthenticationType` in `types/index.d.ts`.
=> Add `sol` to `AuthenticationType` (Typescript)

src/UnitConvert.js
---
---
`Moralis.Units` is not defined, as the export of UnitConverter has been removed during a merge-conflict.
Exporting `UnitConverter`
=> fix: export for Moralis.Units

src/Web3Connector/WalletConnectWeb3Connector.js
Prevent an error where walletconnect provider is not defined yet while
calling disconnect
---
---
=> fix: prevent walletconnect disconnect error

src/Parse.js
---
---
Moralis.start is being stuck if unpk is not responsing
Remove the await to let the start function being finished without this check
=> fix: prevent loading issue when unpkg is down

src/InternalWeb3Provider.js, src/MoralisWeb3.js
---
---
Moralis.enableWeb3 could be called multiple times after eachother. This results in cleaning up the provider, and creating one at the same time. And results in an invalid state of Moralis, where the InternalWeb3Connector has no connector.
Add a boolean, to check when Moralis.enableWeb3 is in process, and throw an error if a user calls enableWeb3 again before the previous call is finished
=> fix: avoid duplicate enableWeb3 calls

scripts/generateSolanaApiTypes.js, scripts/generateWeb3ApiTypes.js, types/generated/web3Api.d.ts
---
---
Related issue: https://github.com/MoralisWeb3/Moralis-JS-SDK/pull/235
- Generate correct web3API types when only path param is required
- Aligned solanaAPI and web3API types generation to avoid future issues
=> fix: type gen for web3Api when no queryparam

src/MoralisWeb3.js, src/Web3Connector/MagicWeb3Connector.js, src/Web3Connector/WalletConnectWeb3Connector.js
---
---
Refreshing the page will reset walletconnect session
Don't clear the session, and make it optional by calling a cleanup function. Also removed the `deactivate` function call upon calling enableWeb3.
Now the behaviour is more consistent across the connectors and the user can deactivate by calling the `deactivate` manually or closing the session in the respective wallet-app
=> fix: preserve sessions for walletconnect and magic

src/ParseUser.js, src/__tests__/ParseUser-test.js
---
---
Web3 does not gets cleaned up on logout, as the reference to MoralisWeb3 is different than Moralis
Call cleanup on the Moralis class instance
=> fix: cleanup web3 on logout

src/InternalWeb3Provider.js, src/MoralisWeb3.js
---
---
EthersJs throws an error if the backend chain changes (for example Metamask)
Allow the setting 'any' network ( as described in https://github.com/ethers-io/ethers.js/issues/866) via the `anyNetwork` option when calling `authenticate` or `enableWeb3`
=> fix: expose setting of 'any' network on  provider

src/MoralisWeb3.js
---
---
Metamask might disconnect when switching to a chain (example some Binance Testnet rpcs). In this case, metamask will automatically try to reconnect
Do not call `cleanup` if metamask disconnects with the message that it will try to reconnect. Let metamask try to reconnect instead.
=> fix: account for metamask disconnect issue

src/Web3Connector/MagicWeb3Connector.js, src/Web3Connector/WalletConnectWeb3Connector.js
---
---
Now that sessions are preserved between connections, we need a way for the user to indicate if they want to force a new session.
Ex. When they want to force the user to scan a new qr code via WalletConnect
Add a `newSession` prop for walletconnect and magic, to allow this behaviour.
=> fix: newsession param for walletconnect and magic

src/Parse.js, src/__tests__/browser-test.js
If using require('moralis') on node.js, the error message should provide the correct require command.  Updated to use moralis module (previously parse)
---
---
- [x ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [ x] My code is conform the [code style](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CODE_STYLE.md)
- [ x] I have made corresponding changes to the documentation
- [ x] I have updated Typescript definitions when needed
The log message if the wrong version of the Moralis module is used with nodej.js provides the incorrect solution
Updated the log message to include the correct require command.
=> update log message if running on node.js

.changeset/purple-lemons-wink.md, packages/core/src/dataTypes/EvmChain.ts
fix chain name to id map. ropsten and rinkeby pointed to incorrect id
---
---
=> fix(core): chainNameToChainIdMap

packages/core/src/dataTypes/EvmAddress.ts, packages/core/src/dataTypes/EvmChain.ts
Some datatypes have separate validation methods. This results in
duplicate logic, as we also validate during the parse. This PR puts
validation just in the parse function
---
---
=> perf(datatypes): cleanup validations

.changeset/shaggy-ways-fry.md, demos/test-cdn/public/demo.esm.html, demos/test-cdn/public/demo.umd.html, packages/core/src/environment/isTest.ts, rollup.config.js
---
name: parse fixed for UMD/ESM builds.
---
=> parse fixed for UMD/ESM builds.

.changeset/soft-snails-smell.md, packages/apiUtils/package.json, packages/auth/package.json, packages/core/package.json, packages/evmApi/package.json, packages/evmUtils/package.json, packages/moralis/package.json, packages/solApi/package.json, packages/solUtils/package.json
=> fix: include all lib files in npm builds

.changeset/fresh-phones-trade.md, packages/evmApi/src/generated/types.ts, packages/evmApi/src/resolvers/native/getContractEvents.ts
---
---
Update types and resolvers according to latest swagger docs
=> feat: update api types

.changeset/clever-pens-build.md, packages/evmApi/src/resolvers/token/getNFTMetadata.ts, packages/evmUtils/src/dataTypes/EvmNftMetadata/types.ts
---
name: nullable contractType for getNFTMetadata.
---
=> fix: nullable contractType for getNFTMetadata.

.changeset/beige-onions-tan.md, packages/integration/mockRequests/solApi/getNFT.ts, packages/integration/test/solApi/getBalance.test.ts, packages/integration/test/solApi/getMetadata.test.ts, packages/integration/test/solApi/getNFT.test.ts, packages/integration/test/solApi/getPortfolio.test.ts, packages/integration/test/solApi/getSPL.test.ts, packages/solUtils/package.json, packages/solUtils/src/dataTypes/SolAddress/SolAddress.test.ts, packages/solUtils/src/dataTypes/SolAddress/SolAddress.ts, typedoc.json, yarn.lock
---
name: SolAddress docs.
---
=> solana address validation + docs.

.changeset/nine-donuts-doubt.md, packages/core/src/controllers/AxiosRetry.ts, packages/core/src/controllers/RequestController.ts, packages/core/src/controllers/RequestController/ApiRequestError.ts, packages/core/src/controllers/RequestController/RequestController.ts, packages/core/src/controllers/RequestController/index.ts, packages/integration/test/core/requestController/requestControllerGet.test.ts
---
---
Parse API errors when api returns a 'message' in the error response
=> Fix parse api errors

.changeset/gorgeous-plants-exercise.md, packages/evmUtils/src/dataTypes/EvmChain/EvmChain.ts, packages/solUtils/src/dataTypes/SolNetwork/SolNetwork.test.ts, packages/solUtils/src/dataTypes/SolNetwork/SolNetwork.ts
---
---
- Deprecate old EVM testnets
- Add enums for SolNetwork
=> Update chain enums

.changeset/grumpy-eels-mix.md, packages/evmApi/src/resolvers/token/getTokenPrice.ts, packages/integration/mockRequests/evmApi/getTokenPrice.ts, packages/integration/test/evmApi/getTokenPrice.test.ts
---
name: fixed TypeScript definition for the getTokenPrice method
---
=> fixed TypeScript definition for getTokenPrice method

.changeset/gold-dryers-appear.md, packages/streams/src/index.ts, packages/streams/src/methods/getById.ts, packages/streams/src/methods/types.ts, packages/streams/src/resolvers/evmStreams/types.ts, packages/streams/src/resolvers/history/getHistory.ts, packages/streams/src/resolvers/history/replayHistory.ts, packages/streams/src/resolvers/history/types.ts, packages/streams/src/resolvers/project/setSettings.ts, packages/streams/src/resolvers/project/types.ts
---
---
Export Streams method types
=> Export streams types

demos/cli/package.json
---
name: 'cli demo: add typescript as dev dependency'
---
When building [*cli* demo](https://github.com/MoralisWeb3/Moralis-JS-SDK/tree/main/demos/cli) without Typescript globally installed, I'm getting this error:
```shell
~/Desktop/cli via  v18.11.0 
➜ yarn run build
yarn run v1.22.19
$ tsc
/bin/sh: line 1: tsc: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
After adding to [`package.json`](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/demos/cli/package.json) / devDependencies the `"typescript": "^4.8.4"` I'm able to build without problems:
```shell
~/Desktop/cli via  v18.11.0 took 6s 
➜ yarn run build
yarn run v1.22.19
$ tsc
Done in 1.10s.
```
=> cli demo: add typescript as dev dependency

packages/common/evmUtils/src/operations/operations.test.ts, packages/common/evmUtils/src/operations/token/getWalletTokenTransfersOperation.ts, packages/common/evmUtils/src/operations/utils/runContractFunctionOperation.ts, packages/common/solUtils/src/operations/operations.test.ts, packages/testUtils/src/index.ts, packages/testUtils/src/openapi/index.ts, packages/testUtils/src/operations/OpenApiInterfaceReader.ts, packages/testUtils/src/operations/OperationDefinitionReader.ts, packages/testUtils/src/operations/TsNodeWalker.ts, packages/testUtils/src/operations/index.ts
---
name: validate return property names for getRequestUrlParams() methods.
---
=> validate return property names for getRequestUrlParams() methods.

demos/firebase-proxy/functions/tsconfig.json, packages/apiUtils/src/config/MoralisConfig.ts, packages/apiUtils/src/config/index.ts, packages/common/core/src/Config/MoralisConfig.ts, packages/common/core/src/Core.ts, packages/common/core/src/dataTypes/BigNumber/index.ts, packages/moralis/src/Config/MoralisConfig.ts, packages/moralis/src/config/MoralisConfig.ts, packages/moralis/src/index.ts
---
name: 'common-core parameters not using all possible options from umbrella'
---
This PR solves that when starting the common core package you are offered to pass an apiKey, which is not needed and should not be used on FE
=> separate common-core and umbrella package configs

demos/nextjs/pages/api/moralis/[...moralis].ts
---
about: Added missing [...moralis].ts file in NextJS Demo
---
Looks like we've lost this file in some commit.
=> Fix: missing moralis api handler in demo added

.changeset/funny-sheep-fold.md, packages/common/evmUtils/src/operations/nft/getContractNFTsOperation.test.ts, packages/common/evmUtils/src/operations/nft/getContractNFTsOperation.ts, packages/common/evmUtils/src/operations/nft/getNFTMetadataOperation.test.ts, packages/common/evmUtils/src/operations/nft/getNFTMetadataOperation.ts, packages/common/evmUtils/src/operations/nft/getNFTOwnersOperation.test.ts, packages/common/evmUtils/src/operations/nft/getNFTOwnersOperation.ts, packages/common/evmUtils/src/operations/nft/getNFTTokenIdOwnersOperation.test.ts, packages/common/evmUtils/src/operations/nft/getNFTTokenIdOwnersOperation.ts, packages/common/evmUtils/src/operations/nft/getWalletNFTsOperation.test.ts, packages/common/evmUtils/src/operations/nft/getWalletNFTsOperation.ts
---
---
In some places, the parameter "normalizeMetadata" was missing
=> Fix: added missing 'normalizeMetadata' param

.changeset/soft-bananas-applaud.md, demos/nextjs/app/components/modules/Authentication/Authentication.tsx, demos/nextjs/app/components/modules/Profile/Profile.tsx, packages/next/src/auth/MoralisNextAuthProvider.ts
---
name: added payload parameter to MoralisNextAuthProvider.
---
=> feat: added payload parameter to MoralisNextAuthProvider.

packages/next/package.json, packages/next/src/MoralisNextApi/MoralisNextApi.ts, packages/next/src/auth/MoralisNextAuthProvider.ts, packages/next/src/serverLogger.ts, packages/next/src/utils/fetchers/fetcher.ts, yarn.lock
---
---
- All errors show up as a generic 500 error
- Use statusCode from the MoralisApi, otherwise if it's a user error return 400, otherwise return 500 with a default message
- Add a serverLogger to the nextApi, to log any unaccounted errors
- Resolve errors client-side when the NextJs returns an {error: 'some error'} response
=> fix: return proper error messages in nextjs

.changeset/nervous-doors-kick.md, packages/streams/src/methods/addAddress.ts, packages/streams/src/methods/create.ts, packages/streams/src/methods/delete.ts, packages/streams/src/methods/deleteAddress.ts, packages/streams/src/methods/getAddresses.ts, packages/streams/src/methods/getAll.ts, packages/streams/src/methods/getById.ts, packages/streams/src/methods/update.ts, packages/streams/src/methods/updateStatus.ts, packages/streams/src/utils/StreamNetwork.ts, packages/streams/src/utils/commonNetworkOptions.ts
---
---
`getStreamById` does not default to 'evm'.
- Moved shared logic
- Default to evm for `getStreamById`
- Fix error message when wrong networkType is provided, as we don't support Solana for streams
- deprecate network option in favour of networkType for `getStreamById` for consistency with other streams/auth methods
=> fix: consistent networkTypes fallback for streams

.changeset/forty-dragons-act.md, packages/auth/src/Auth.ts
---
---
After changing the logic of resolving operations in  NextJs, we have an issue. Auth is handled a bit different, as we don't export the resolvers directly, but rather a combined function.
Two possible solutions:
1. Change the NextJs hook to be compatible with `requestMessage` and pass the network as a parameter. Then we need to update `packages/next/src/MoralisNextApi/Modules.ts` to account for a "different kind" of operation resolver (not grouped)
2. Add additional groups/operations to Auth, that is compatible with swagger/our operations structure. 
I choose option 2 as it is more predictable and does not involve a breaking change in the NextJs package. In the future we could improve it by extending Auth from a ClientEvmAuth and …
=> fix: resolving requestChallenge hooks

.changeset/old-spoons-buy.md, packages/apiUtils/src/resolvers2/OperationRequestBuilder.test.ts, packages/apiUtils/src/resolvers2/OperationRequestBuilder.ts, packages/evmApi/integration/mocks/endpoints/getContractNFTs.ts, packages/evmApi/integration/test/getContractNFTs.test.ts
---
name: support false value in query parameters.
---
=> fix: support false value in query parameters.

.changeset/funny-rocks-invent.md, packages/common/streamsUtils/src/operations/evmStreams/updateStreamEvmOperation.test.ts, packages/common/streamsUtils/src/operations/evmStreams/updateStreamEvmOperation.ts, packages/streams/integration/mocks/endpoints/evm/updateStream.ts, packages/streams/integration/test/updateStream.test.ts
---
name: fix: optional `chains` property for the EVM Streams API.
---
=> fix: optional `chains` property for the EVM Streams API.

.changeset/afraid-buses-tell.md, packages/apiUtils/tsconfig.json, packages/aptosApi/tsconfig.json, packages/auth/tsconfig.json, packages/common/aptosUtils/tsconfig.json, packages/common/authUtils/tsconfig.json, packages/common/core/tsconfig.json, packages/common/evmUtils/tsconfig.json, packages/common/solUtils/tsconfig.json, packages/common/streamsUtils/tsconfig.json, packages/evmApi/tsconfig.json, packages/evmUtils/tsconfig.json, packages/moralis/tsconfig.json, packages/solApi/tsconfig.json, packages/solUtils/tsconfig.json, packages/streams/tsconfig.json, tsconfig.package.json
---
name: restored CommonJS bundle format.
---
=> restored CommonJS bundle format.

.changeset/purple-rocks-punch.md, packages/common/evmUtils/src/data/chaindata.ts, packages/common/evmUtils/src/dataTypes/EvmChain/EvmChain.test.ts, packages/common/evmUtils/src/dataTypes/EvmChain/EvmChain.ts
This PR adds support for Moonbeam chain
=> Feat: add support for moonbeam chain

.changeset/seven-rockets-crash.md, packages/common/evmUtils/src/data/chaindata.ts, packages/common/evmUtils/src/dataTypes/EvmChain/EvmChain.test.ts, packages/common/evmUtils/src/dataTypes/EvmChain/EvmChain.ts
This PR implements support for Moonbase chain
=> Feat: Support for Moonbase chain

.changeset/beige-plants-retire.md, packages/common/evmUtils/src/data/chaindata.ts, packages/common/evmUtils/src/dataTypes/EvmChain/EvmChain.test.ts, packages/common/evmUtils/src/dataTypes/EvmChain/EvmChain.ts
This PR implements support Linea Sepolia
=> Feat: Linea sepolia
